# Form implementation generated from reading ui file '/media/uos/1384DF358184FD3D/测试/qt/PythonCompiler.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PythonCompiler(object):
    def setupUi(self, PythonCompiler):
        PythonCompiler.setObjectName("PythonCompiler")
        PythonCompiler.resize(540, 320)
        PythonCompiler.setMinimumSize(QtCore.QSize(540, 320))
        PythonCompiler.setMaximumSize(QtCore.QSize(540, 320))
        PythonCompiler.setBaseSize(QtCore.QSize(540, 320))
        PythonCompiler.setWindowTitle("PythonCompiler")
        PythonCompiler.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=PythonCompiler)
        self.buttonBox.setGeometry(QtCore.QRect(290, 270, 240, 40))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(parent=PythonCompiler)
        self.label.setGeometry(QtCore.QRect(20, 20, 171, 22))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=PythonCompiler)
        self.label_2.setGeometry(QtCore.QRect(350, 20, 50, 25))
        self.label_2.setObjectName("label_2")
        self.specify_link = QtWidgets.QCheckBox(parent=PythonCompiler)
        self.specify_link.setGeometry(QtCore.QRect(20, 60, 192, 25))
        self.specify_link.setObjectName("specify_link")
        self.opt = QtWidgets.QCheckBox(parent=PythonCompiler)
        self.opt.setGeometry(QtCore.QRect(30, 100, 180, 26))
        self.opt.setChecked(True)
        self.opt.setObjectName("opt")
        self.ssl = QtWidgets.QCheckBox(parent=PythonCompiler)
        self.ssl.setGeometry(QtCore.QRect(330, 135, 191, 26))
        self.ssl.setChecked(True)
        self.ssl.setObjectName("ssl")
        self.lto = QtWidgets.QCheckBox(parent=PythonCompiler)
        self.lto.setGeometry(QtCore.QRect(30, 135, 300, 25))
        self.lto.setChecked(True)
        self.lto.setObjectName("lto")
        self.shared = QtWidgets.QCheckBox(parent=PythonCompiler)
        self.shared.setGeometry(QtCore.QRect(330, 100, 191, 26))
        self.shared.setChecked(True)
        self.shared.setObjectName("shared")
        self.label_3 = QtWidgets.QLabel(parent=PythonCompiler)
        self.label_3.setGeometry(QtCore.QRect(20, 220, 50, 25))
        self.label_3.setObjectName("label_3")
        self.specify_c = QtWidgets.QCheckBox(parent=PythonCompiler)
        self.specify_c.setGeometry(QtCore.QRect(225, 220, 160, 25))
        self.specify_c.setObjectName("specify_c")
        self.mirror = QtWidgets.QComboBox(parent=PythonCompiler)
        self.mirror.setGeometry(QtCore.QRect(400, 20, 120, 25))
        self.mirror.setEditable(True)
        self.mirror.setFrame(True)
        self.mirror.setObjectName("mirror")
        self.prefix = QtWidgets.QLineEdit(parent=PythonCompiler)
        self.prefix.setGeometry(QtCore.QRect(70, 220, 80, 25))
        self.prefix.setObjectName("prefix")
        self.cc = QtWidgets.QLineEdit(parent=PythonCompiler)
        self.cc.setEnabled(False)
        self.cc.setGeometry(QtCore.QRect(385, 220, 135, 25))
        self.cc.setText("")
        self.cc.setObjectName("cc")
        self.download = QtWidgets.QLineEdit(parent=PythonCompiler)
        self.download.setEnabled(False)
        self.download.setGeometry(QtCore.QRect(200, 60, 320, 25))
        self.download.setTabletTracking(False)
        self.download.setAutoFillBackground(False)
        self.download.setInputMask("")
        self.download.setText("")
        self.download.setFrame(True)
        self.download.setDragEnabled(False)
        self.download.setReadOnly(False)
        self.download.setClearButtonEnabled(False)
        self.download.setObjectName("download")
        self.selection = QtWidgets.QComboBox(parent=PythonCompiler)
        self.selection.setGeometry(QtCore.QRect(190, 20, 100, 25))
        self.selection.setEditable(True)
        self.selection.setDuplicatesEnabled(False)
        self.selection.setObjectName("selection")
        self.pushButton = QtWidgets.QPushButton(parent=PythonCompiler)
        self.pushButton.setGeometry(QtCore.QRect(20, 275, 64, 30))
        self.pushButton.setCheckable(False)
        self.pushButton.setObjectName("pushButton")
        self.configuration = QtWidgets.QLineEdit(parent=PythonCompiler)
        self.configuration.setEnabled(False)
        self.configuration.setGeometry(QtCore.QRect(225, 180, 295, 25))
        self.configuration.setTabletTracking(False)
        self.configuration.setAutoFillBackground(False)
        self.configuration.setInputMask("")
        self.configuration.setText("")
        self.configuration.setFrame(True)
        self.configuration.setDragEnabled(False)
        self.configuration.setReadOnly(False)
        self.configuration.setClearButtonEnabled(False)
        self.configuration.setObjectName("configuration")
        self.customize = QtWidgets.QCheckBox(parent=PythonCompiler)
        self.customize.setGeometry(QtCore.QRect(20, 180, 225, 25))
        self.customize.setObjectName("customize")
        self.label.setBuddy(self.selection)
        self.label_2.setBuddy(self.mirror)
        self.label_3.setBuddy(self.prefix)

        self.retranslateUi(PythonCompiler)
        self.specify_link.clicked['bool'].connect(self.download.setEnabled) # type: ignore
        self.specify_c.clicked['bool'].connect(self.cc.setEnabled) # type: ignore
        self.specify_link.clicked['bool'].connect(self.mirror.setDisabled) # type: ignore
        self.customize.clicked['bool'].connect(self.opt.setDisabled) # type: ignore
        self.customize.clicked['bool'].connect(self.shared.setDisabled) # type: ignore
        self.customize.clicked['bool'].connect(self.lto.setDisabled) # type: ignore
        self.customize.clicked['bool'].connect(self.ssl.setDisabled) # type: ignore
        self.customize.clicked['bool'].connect(self.configuration.setEnabled) # type: ignore
        self.specify_link.clicked['bool'].connect(self.cc.setDisabled) # type: ignore
        self.customize.clicked['bool'].connect(self.specify_c.setDisabled) # type: ignore
        self.customize.clicked['bool'].connect(self.cc.setDisabled) # type: ignore
        self.customize.clicked['bool'].connect(self.prefix.setDisabled) # type: ignore
        self.customize.clicked['bool'].connect(self.label_3.setDisabled) # type: ignore
        self.specify_link.clicked['bool'].connect(self.label_2.setDisabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(PythonCompiler)

    def retranslateUi(self, PythonCompiler):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("PythonCompiler", "Required Python Version: "))
        self.label_2.setText(_translate("PythonCompiler", "Mirror: "))
        self.specify_link.setText(_translate("PythonCompiler", "Specify download link: "))
        self.opt.setText(_translate("PythonCompiler", "Enable optimizations"))
        self.ssl.setText(_translate("PythonCompiler", "Build with SSL"))
        self.lto.setText(_translate("PythonCompiler", "Build with Link-time-optimizations (LTO)"))
        self.shared.setText(_translate("PythonCompiler", "Enable shared libraries"))
        self.label_3.setText(_translate("PythonCompiler", "Prefix: "))
        self.specify_c.setText(_translate("PythonCompiler", "Specify C Compiler: "))
        self.prefix.setText(_translate("PythonCompiler", "/usr"))
        self.pushButton.setText(_translate("PythonCompiler", "About"))
        self.customize.setText(_translate("PythonCompiler", "Customize configurations: "))
